### ISSUE TITLE
Файлы 

### ISSUE THREAD

**Issue by biznesup** [fandaymon/majordomo-tuya#1]
Надо было добавить .apk файлы обеих прог(Packet Capture, TuyaSmart. ). С последними нифига не работает. ..
Packet Capture не  грузит  certificat AC,
И все пакеты от TuyaSmart маркирует как ssl no data. Может какую хитрость рассказать забыли?

**Comment by fandaymon** [comment]
Теперь модуль берёт локальные ключи из оригинального облака - в apk нет необходимости
