### ISSUE TITLE
Сортировка

### ISSUE THREAD

**Issue by kirush0280** [fandaymon/majordomo-tuya#2]
Можно ли добавить порядок сортировки либо возможность группировки устройств либо сортировка по типу оборудования?
При большом кол-ве устройств очень не удобно искать становится.

**Comment by fandaymon** [comment]
Могу добавить при выводе устройств сортировку по тип + название
С группировкой сложнее - надо добавлять группы, где-то хранить какая группы скрыта, какая раскрыта...

**Comment by kirush0280** [comment]
хотя бы по типу, а в каждом типе по алфавиту например. было бы здорово

**Comment by kirush0280** [comment]
спасибо большое
